### ISSUE TITLE
Multi chain protein trajectory

### ISSUE THREAD

**Issue by avinashkarkada** [juexinwang/NRI-MD#10]
Hi,
Is there any way to use a multi chain protein MD trajectory?
I noticed that the script throws the following error when my ca pdb file contains chain identifiers:

**Generate Train
Start: 1th PDB
Traceback (most recent call last):
  File "convert_dataset.py", line 345, in <module>
    feature_size=feature_size, num_residues=num_residues, interval=train_interval, pdb_start=pdb_start, pdb_end=pdb_end, aa_start=1, aa_end=num_residues)
  File "convert_dataset.py", line 305, in convert_dataset_md_single
    i)+".pdb", timestep_size, feature_size, num_residues, interval, j, aa_start, aa_end))
  File "convert_dataset.py", line 127, in read_feature_MD_file_slidingwindow
    elif(line.startswith("ATOM") and words[2] == "CA" and int(words[4]) >= aa_start and int(words[4]) <= aa_end and flag):
ValueError: invalid literal for int() with base 10: 'A'**

**Comment by juexinwang** [comment]
Thanks for you reporting this issue. Currently, we only support one chain
trajectory.

**Comment by avinashkarkada** [comment]
Got it. Thank you for your reply
